export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';